import { Layout } from "@/components/layout/Layout";
import "./globals.css";
import type { Metadata } from "next";
import { Alexandria } from "next/font/google";

const alexandria = Alexandria({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JSONPlaceholder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={alexandria.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
